"""initial schema

Revision ID: 57f22fdb80b5
Revises: 
Create Date: 2026-07-01 15:52:29.078559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57f22fdb80b5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_listings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('listing_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('species', sa.String(), nullable=True),
    sa.Column('breed', sa.String(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('photo_phash', sa.String(), nullable=True),
    sa.Column('source_name', sa.String(), nullable=False),
    sa.Column('is_certified', sa.Boolean(), nullable=False),
    sa.Column('relevance_score_base', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_listings_listing_type'), 'catalog_listings', ['listing_type'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_users_role', 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('caregivers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('role_type', sa.String(), nullable=False),
    sa.Column('accepted_species', sa.String(), nullable=True),
    sa.Column('accepted_sizes', sa.String(), nullable=True),
    sa.Column('can_administer_medication', sa.Boolean(), nullable=True),
    sa.Column('specialization', sa.String(), nullable=True),
    sa.Column('id_document_url', sa.String(), nullable=True),
    sa.Column('id_verification_status', sa.String(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('receives_alerts', sa.Boolean(), nullable=True),
    sa.Column('rating_average', sa.Float(), nullable=True),
    sa.Column('rating_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_caregivers_public', 'caregivers', ['is_public'], unique=False)
    op.create_index('idx_caregivers_role', 'caregivers', ['role_type'], unique=False)
    op.create_index(op.f('ix_caregivers_user_id'), 'caregivers', ['user_id'], unique=True)
    op.create_table('image_searches',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('intent', sa.String(), nullable=False),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification_preferences',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('radius_km', sa.Float(), nullable=False),
    sa.Column('push_enabled', sa.Boolean(), nullable=True),
    sa.Column('sms_enabled', sa.Boolean(), nullable=True),
    sa.Column('email_enabled', sa.Boolean(), nullable=True),
    sa.Column('alerts_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_preferences_user_id'), 'notification_preferences', ['user_id'], unique=True)
    op.create_table('pets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('species', sa.String(), nullable=False),
    sa.Column('breed', sa.String(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=False),
    sa.Column('photo_phash', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('microchip_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pets_owner', 'pets', ['owner_id'], unique=False)
    op.create_index('idx_pets_species', 'pets', ['species'], unique=False)
    op.create_index(op.f('ix_pets_name'), 'pets', ['name'], unique=False)
    op.create_index(op.f('ix_pets_owner_id'), 'pets', ['owner_id'], unique=False)
    op.create_table('caregiver_ratings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('caregiver_id', sa.String(), nullable=False),
    sa.Column('rater_id', sa.String(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['caregiver_id'], ['caregivers.id'], ),
    sa.ForeignKeyConstraint(['rater_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_caregiver_ratings_caregiver_id'), 'caregiver_ratings', ['caregiver_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('pet_id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('last_seen_latitude', sa.Float(), nullable=False),
    sa.Column('last_seen_longitude', sa.Float(), nullable=False),
    sa.Column('last_seen_address', sa.String(), nullable=True),
    sa.Column('last_seen_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('alert_radius_km', sa.Float(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('contact_is_anonymous', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('found_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reports_location', 'reports', ['last_seen_latitude', 'last_seen_longitude'], unique=False)
    op.create_index('idx_reports_status_owner', 'reports', ['status', 'owner_id'], unique=False)
    op.create_index(op.f('ix_reports_owner_id'), 'reports', ['owner_id'], unique=False)
    op.create_index(op.f('ix_reports_pet_id'), 'reports', ['pet_id'], unique=False)
    op.create_index(op.f('ix_reports_status'), 'reports', ['status'], unique=False)
    op.create_table('sightings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('report_id', sa.String(), nullable=False),
    sa.Column('citizen_id', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('photo_url', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('confidence_level', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['citizen_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sightings_location', 'sightings', ['latitude', 'longitude'], unique=False)
    op.create_index('idx_sightings_report', 'sightings', ['report_id'], unique=False)
    op.create_index(op.f('ix_sightings_citizen_id'), 'sightings', ['citizen_id'], unique=False)
    op.create_index(op.f('ix_sightings_report_id'), 'sightings', ['report_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('report_id', sa.String(), nullable=True),
    sa.Column('sighting_id', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.ForeignKeyConstraint(['sighting_id'], ['sightings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_report_id'), 'notifications', ['report_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_report_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_sightings_report_id'), table_name='sightings')
    op.drop_index(op.f('ix_sightings_citizen_id'), table_name='sightings')
    op.drop_index('idx_sightings_report', table_name='sightings')
    op.drop_index('idx_sightings_location', table_name='sightings')
    op.drop_table('sightings')
    op.drop_index(op.f('ix_reports_status'), table_name='reports')
    op.drop_index(op.f('ix_reports_pet_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_owner_id'), table_name='reports')
    op.drop_index('idx_reports_status_owner', table_name='reports')
    op.drop_index('idx_reports_location', table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_caregiver_ratings_caregiver_id'), table_name='caregiver_ratings')
    op.drop_table('caregiver_ratings')
    op.drop_index(op.f('ix_pets_owner_id'), table_name='pets')
    op.drop_index(op.f('ix_pets_name'), table_name='pets')
    op.drop_index('idx_pets_species', table_name='pets')
    op.drop_index('idx_pets_owner', table_name='pets')
    op.drop_table('pets')
    op.drop_index(op.f('ix_notification_preferences_user_id'), table_name='notification_preferences')
    op.drop_table('notification_preferences')
    op.drop_table('image_searches')
    op.drop_index(op.f('ix_caregivers_user_id'), table_name='caregivers')
    op.drop_index('idx_caregivers_role', table_name='caregivers')
    op.drop_index('idx_caregivers_public', table_name='caregivers')
    op.drop_table('caregivers')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_users_role', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_catalog_listings_listing_type'), table_name='catalog_listings')
    op.drop_table('catalog_listings')
    # ### end Alembic commands ###
